
learner         :       GSA_EMA
optim           :       Adam
learning_rate   :       0.0005
momentum        :       0
weight_decay    :       0
dataset         :       cifar10
n_tasks         :       5
mem_size        :       500
mem_batch_size  :       64
batch_size      :       10
nf              :       64
tf_type         :       partial
training_type   :       inc
kd_lambda       :       8
n_teacher       :       2
alpha_min       :       0.005
alpha_max       :       0.1
