
learner         :       MMKD
optim           :       Adam
learning_rate   :       0.0005
momentum        :       0
weight_decay    :       0
dataset         :       cifar100
n_tasks         :       10
mem_size        :       5000
mem_batch_size  :       64
batch_size      :       10
nf              :       64
tf_type         :       full
training_type   :       inc
kd_lambda       :       8
n_teacher       :       2
alpha_min       :       0.005
alpha_max       :       0.1
