
learner         :       OCMEMA
dataset         :       tiny
n_tasks         :       100
mem_size        :       10000
mem_batch_size  :       64
batch_size      :       10
proj_dim        :       128
nf              :       64
supervised      :       True
kd_lambda       :       8
n_teacher       :       2
alpha_min       :       0.005
alpha_max       :       0.1
