
learner         :       DERpp_SDP
optim           :       Adam
learning_rate   :       0.0001
momentum        :       0
weight_decay    :       0
derpp_alpha     :       0.2
derpp_beta      :       1.0
dataset         :       imagenet100
n_tasks         :       20
mem_size        :       5000
mem_batch_size  :       64
batch_size      :       10
nf              :       64
training_type   :       blurry
blurry_scale    :       500
sdp_c2          :       0.75
sdp_mu          :       100
