
learner         :       DERppEMA
optim           :       Adam
learning_rate   :       0.0001
momentum        :       0
weight_decay    :       0
derpp_alpha     :       0.2
derpp_beta      :       1.0
dataset         :       cifar100
n_tasks         :       10
mem_size        :       1000
mem_batch_size  :       64
batch_size      :       10
nf              :       64
training_type   :       inc
kd_lambda       :       5.5
n_teacher       :       1
alpha_min       :       0.01
alpha_max       :       0.01
