
learner         :       DERpp_SDP
optim           :       Adam
learning_rate   :       0.0001
momentum        :       0
weight_decay    :       0
derpp_alpha     :       0.2
derpp_beta      :       1.0
dataset         :       cifar10
n_tasks         :       5
mem_size        :       500
mem_batch_size  :       64
batch_size      :       10
nf              :       64
training_type   :       inc
sdp_c2          :       0.75
sdp_mu          :       100
