
learner         :       DERppEMA
optim           :       Adam
learning_rate   :       0.0001
momentum        :       0
weight_decay    :       0
derpp_alpha     :       0.2
derpp_beta      :       1.0
dataset         :       tiny
n_tasks         :       100
mem_size        :       10000
mem_batch_size  :       64
batch_size      :       10
nf              :       64
training_type   :       blurry
blurry_scale    :       500
kd_lambda       :       5.5
n_teacher       :       1
alpha_min       :       0.01
alpha_max       :       0.01
