
learner         :       OCMEMA
training_type   :       inc
dataset         :       cifar10
n_tasks         :       5
mem_size        :       1000
mem_batch_size  :       64
batch_size      :       10
proj_dim        :       128
nf              :       64
supervised      :       True
kd_lambda       :       5.5
n_teacher       :       1
alpha_min       :       0.01
alpha_max       :       0.01
